"""Real PostgreSQL integration tests for the stage approval HTTP API.

Drives the real application end to end over HTTP with the deterministic
"local" LLM and embeddings providers and no Tavily key. Every workspace
here has all seven stages generated by a real full-strategy run, so each
approval is pinned to a genuine record id and version.

The LLM gateway is wrapped in a counting proxy: approving, reading, and
revoking must cost zero model calls. The service rules behind these
routes (idempotency, race handling, the prerequisite gate) are covered in
test_stage_approval_service_integration.py; this file is about the HTTP
surface and how it reflects into the strategy status.
"""

import os
from collections.abc import Iterator
from dataclasses import dataclass
from typing import Any
from uuid import UUID, uuid4

import pytest
from fastapi.testclient import TestClient
from sqlalchemy import select

from backend.app.config import Settings
from backend.app.db.database import Database
from backend.app.db.models.market_research import MarketResearch
from backend.app.db.models.stage_approval import StageApproval
from backend.app.db.models.workspace import Workspace
from backend.app.llm.gateway import LLMGateway
from backend.app.main import create_application
from backend.app.schemas.strategy_orchestration import StrategyStage

RUN_INTEGRATION_TESTS = os.getenv("GROWTHCREW_RUN_INTEGRATION_TESTS") == "1"

pytestmark = [
    pytest.mark.integration,
    pytest.mark.skipif(
        not RUN_INTEGRATION_TESTS,
        reason=("Set GROWTHCREW_RUN_INTEGRATION_TESTS=1 to run PostgreSQL integration tests."),
    ),
]

S = StrategyStage
STAGES = list(StrategyStage)
MR = S.MARKET_RESEARCH


class CountingLLM:
    """Proxy a real LLMGateway, counting its four generation methods."""

    _TRACKED = frozenset({"chat", "chat_with_usage", "structured", "structured_with_usage"})

    def __init__(self, inner: LLMGateway) -> None:
        self._inner = inner
        self.calls = 0

    def __getattr__(self, name: str) -> Any:
        attribute = getattr(self._inner, name)
        if name not in self._TRACKED:
            return attribute

        def tracked(*args: Any, **kwargs: Any) -> Any:
            self.calls += 1
            return attribute(*args, **kwargs)

        return tracked


@dataclass
class Context:
    """An API client, its settings, and the LLM call counter."""

    client: TestClient
    settings: Settings
    llm: CountingLLM

    def url(self, workspace_id: UUID, path: str) -> str:
        return f"/api/v1/workspaces/{workspace_id}/{path}"

    def approvals(self, workspace_id: UUID, stage: str) -> str:
        return self.url(workspace_id, f"approvals/{stage}")


@pytest.fixture
def context() -> Iterator[Context]:
    """Create an API client backed by real PostgreSQL and the local stubs."""

    settings = Settings(
        environment="test",
        llm_provider="local",
        embeddings_provider="local",
        tavily_api_key=None,
    )

    if settings.database_url is None:
        pytest.fail("GROWTHCREW_DATABASE_URL is required for integration tests.")

    llm = CountingLLM(LLMGateway(settings))

    with TestClient(create_application(settings, llm_gateway=llm)) as client:
        yield Context(client=client, settings=settings, llm=llm)


def _cleanup(settings: Settings, workspace_id: UUID) -> None:
    """Remove only test-created data after an integration test."""

    database = Database.from_settings(settings)
    try:
        with database.session() as session:
            workspace = session.get(Workspace, workspace_id)
            if workspace is not None:
                session.delete(workspace)
                session.commit()
    finally:
        database.dispose()


def _new_workspace(ctx: Context, name: str, *, generate: bool) -> UUID:
    """Create a workspace with a profile, optionally with all seven stages generated."""

    response = ctx.client.post("/api/v1/workspaces", json={"name": name})
    assert response.status_code == 201
    workspace_id = UUID(response.json()["id"])

    profile = ctx.client.post(
        ctx.url(workspace_id, "business-profile"),
        json={"business_name": name, "industry": "Healthy Snacks"},
    )
    assert profile.status_code == 201

    if generate:
        run = ctx.client.post(
            ctx.url(workspace_id, "generate-full-strategy"),
            json={"force_regenerate": False},
        )
        assert run.status_code == 200
        assert [item["outcome"] for item in run.json()["stages"]] == ["generated"] * 7

    return workspace_id


@pytest.fixture
def workspace(context: Context) -> Iterator[UUID]:
    """A workspace with every stage generated and nothing approved."""

    workspace_id = _new_workspace(context, "Approval API Co", generate=True)
    yield workspace_id
    _cleanup(context.settings, workspace_id)


@pytest.fixture
def bare_workspace(context: Context) -> Iterator[UUID]:
    """A workspace with a profile but no generated stages."""

    workspace_id = _new_workspace(context, "Approval API Bare Co", generate=False)
    yield workspace_id
    _cleanup(context.settings, workspace_id)


def _status(ctx: Context, workspace_id: UUID) -> dict[str, Any]:
    response = ctx.client.get(ctx.url(workspace_id, "strategy-status"))
    assert response.status_code == 200
    return response.json()


def _stage(ctx: Context, workspace_id: UUID, stage: StrategyStage) -> dict[str, Any]:
    return {item["stage"]: item for item in _status(ctx, workspace_id)["stages"]}[stage.value]


def _approve(ctx: Context, workspace_id: UUID, stage: StrategyStage) -> Any:
    """Approve a stage at the version the status currently reports."""

    version = _stage(ctx, workspace_id, stage)["version"]
    return ctx.client.post(ctx.approvals(workspace_id, stage.value), json={"version": version})


def _change_market_research(settings: Settings, workspace_id: UUID) -> None:
    """Edit the market research record in place, bumping its version."""

    database = Database.from_settings(settings)
    try:
        with database.session() as session:
            record = session.scalars(
                select(MarketResearch).where(MarketResearch.workspace_id == workspace_id)
            ).one()
            record.model_used = "edited-after-approval"
            session.commit()
    finally:
        database.dispose()


def _market_research_id(settings: Settings, workspace_id: UUID) -> UUID:
    database = Database.from_settings(settings)
    try:
        with database.session() as session:
            return session.scalars(
                select(MarketResearch.id).where(MarketResearch.workspace_id == workspace_id)
            ).one()
    finally:
        database.dispose()


def _approval_count(settings: Settings, workspace_id: UUID) -> int:
    database = Database.from_settings(settings)
    try:
        with database.session() as session:
            return len(
                list(
                    session.scalars(
                        select(StageApproval).where(StageApproval.workspace_id == workspace_id)
                    )
                )
            )
    finally:
        database.dispose()


# --- approve -------------------------------------------------------------------------


def test_approve_returns_the_approval_and_status_reflects_it(
    context: Context, workspace: UUID
) -> None:
    """Approving over HTTP is visible in the strategy status straight away."""

    response = _approve(context, workspace, MR)
    body = response.json()

    assert response.status_code == 200
    assert body["workspace_id"] == str(workspace)
    assert body["stage"] == "market_research"
    assert body["approved_version"] == 1
    assert body["source"] == "human"
    assert body["record_id"] == str(_market_research_id(context.settings, workspace))
    assert _stage(context, workspace, MR)["approval"] == "approved"
    assert _status(context, workspace)["next_to_approve"] == "business_understanding"


def test_approving_leaves_the_stage_itself_untouched(context: Context, workspace: UUID) -> None:
    """Approval is recorded beside the artifact: the stage's own response is identical after."""

    before = context.client.get(context.url(workspace, "market-research")).json()

    assert _approve(context, workspace, MR).status_code == 200

    after = context.client.get(context.url(workspace, "market-research")).json()
    assert after == before


def test_approving_twice_is_idempotent(context: Context, workspace: UUID) -> None:
    """A repeat approval succeeds, returns the same approval, and adds nothing."""

    first = _approve(context, workspace, MR).json()
    second = _approve(context, workspace, MR).json()

    assert second == first
    assert _approval_count(context.settings, workspace) == 1


def test_approve_a_stale_version_is_409_and_records_nothing(
    context: Context, workspace: UUID
) -> None:
    """A reviewer can only approve the version they actually looked at."""

    response = context.client.post(
        context.approvals(workspace, "market_research"), json={"version": 2}
    )

    assert response.status_code == 409
    assert response.json() == {
        "detail": (
            "The market research stage is now at version 1, not version 2. "
            "Review the latest version before approving it."
        )
    }
    assert _approval_count(context.settings, workspace) == 0
    assert _stage(context, workspace, MR)["approval"] == "draft"


def test_approve_a_stage_that_was_not_generated_is_404(
    context: Context, bare_workspace: UUID
) -> None:
    """There is nothing to approve before generation."""

    response = context.client.post(
        context.approvals(bare_workspace, "market_research"), json={"version": 1}
    )

    assert response.status_code == 404
    assert response.json() == {"detail": "The market research stage has not been generated yet."}


def test_a_client_cannot_claim_an_automatic_approval(context: Context, workspace: UUID) -> None:
    """The body takes only the version; naming a source is a validation error."""

    response = context.client.post(
        context.approvals(workspace, "market_research"),
        json={"version": 1, "source": "auto"},
    )

    assert response.status_code == 422
    assert _approval_count(context.settings, workspace) == 0


def test_a_whole_review_over_http_approves_the_strategy(context: Context, workspace: UUID) -> None:
    """Approving each stage in chain order walks next_to_approve to the end."""

    for index, stage in enumerate(STAGES):
        assert _status(context, workspace)["next_to_approve"] == stage.value
        assert _approve(context, workspace, stage).status_code == 200
        assert _status(context, workspace)["approved"] is (index == len(STAGES) - 1)

    status = _status(context, workspace)
    assert [item["approval"] for item in status["stages"]] == ["approved"] * 7
    assert status["next_to_approve"] is None


def test_approvals_are_scoped_to_their_workspace(context: Context, workspace: UUID) -> None:
    """Approving in one workspace never approves the same stage in another."""

    other = _new_workspace(context, "Approval API Other Co", generate=True)
    try:
        assert _approve(context, workspace, MR).status_code == 200

        assert _stage(context, workspace, MR)["approval"] == "approved"
        assert _stage(context, other, MR)["approval"] == "draft"
        assert context.client.get(context.approvals(other, "market_research")).status_code == 404
    finally:
        _cleanup(context.settings, other)


# --- get -----------------------------------------------------------------------------


def test_get_returns_the_approval_that_was_made(context: Context, workspace: UUID) -> None:
    """Reading back an approval gives exactly what approving returned."""

    approved = _approve(context, workspace, MR).json()

    response = context.client.get(context.approvals(workspace, "market_research"))

    assert response.status_code == 200
    assert response.json() == approved


def test_get_for_an_unapproved_stage_is_404(context: Context, workspace: UUID) -> None:
    """A draft stage has no approval to return."""

    response = context.client.get(context.approvals(workspace, "market_research"))

    assert response.status_code == 404
    assert response.json() == {"detail": "The market research stage is not approved."}


# --- revoke --------------------------------------------------------------------------


def test_delete_revokes_an_approval(context: Context, workspace: UUID) -> None:
    """Revoking returns the stage to draft and removes the approval."""

    _approve(context, workspace, MR)

    response = context.client.delete(context.approvals(workspace, "market_research"))

    assert response.status_code == 204
    assert response.content == b""
    assert _stage(context, workspace, MR)["approval"] == "draft"
    assert context.client.get(context.approvals(workspace, "market_research")).status_code == 404


def test_delete_is_idempotent(context: Context, workspace: UUID) -> None:
    """Revoking a stage with no approval succeeds, as many times as asked."""

    first = context.client.delete(context.approvals(workspace, "market_research"))
    second = context.client.delete(context.approvals(workspace, "market_research"))

    assert (first.status_code, second.status_code) == (204, 204)


def test_revoking_one_stage_leaves_the_others_approved(context: Context, workspace: UUID) -> None:
    """Approvals are independent per stage."""

    _approve(context, workspace, S.BUSINESS_UNDERSTANDING)
    _approve(context, workspace, MR)

    context.client.delete(context.approvals(workspace, "market_research"))

    assert _stage(context, workspace, S.BUSINESS_UNDERSTANDING)["approval"] == "approved"
    assert _stage(context, workspace, MR)["approval"] == "draft"


# --- regeneration retires approval -------------------------------------------------------


def test_a_changed_stage_loses_its_approval_over_http(context: Context, workspace: UUID) -> None:
    """After the record changes: draft in status, 404 on read, and the old version is refused."""

    assert _approve(context, workspace, MR).status_code == 200
    _change_market_research(context.settings, workspace)

    assert _stage(context, workspace, MR)["approval"] == "draft"
    assert context.client.get(context.approvals(workspace, "market_research")).status_code == 404

    stale = context.client.post(
        context.approvals(workspace, "market_research"), json={"version": 1}
    )
    assert stale.status_code == 409
    assert "now at version 2, not version 1" in stale.json()["detail"]

    fresh = context.client.post(
        context.approvals(workspace, "market_research"), json={"version": 2}
    )
    assert fresh.status_code == 200
    assert fresh.json()["approved_version"] == 2
    assert _approval_count(context.settings, workspace) == 1


# --- not found and validation ----------------------------------------------------------


def test_unknown_workspace_is_404_for_every_method(context: Context) -> None:
    """A workspace that does not exist has no approvals to make, read, or revoke."""

    url = context.approvals(uuid4(), "market_research")

    responses = [
        context.client.post(url, json={"version": 1}),
        context.client.get(url),
        context.client.delete(url),
    ]

    assert [item.status_code for item in responses] == [404, 404, 404]
    assert all(item.json() == {"detail": "Workspace not found."} for item in responses)


def test_the_business_profile_is_not_an_approvable_stage(context: Context, workspace: UUID) -> None:
    """Only generated stages have approvals; the profile is rejected by validation."""

    url = context.approvals(workspace, "business_profile")

    responses = [
        context.client.post(url, json={"version": 1}),
        context.client.get(url),
        context.client.delete(url),
    ]

    assert [item.status_code for item in responses] == [422, 422, 422]


# --- cost ------------------------------------------------------------------------------


def test_approving_reading_and_revoking_make_no_llm_calls(
    context: Context, workspace: UUID
) -> None:
    """The whole approval lifecycle is free: no model call, retrieval, or web search."""

    baseline = context.llm.calls

    for stage in STAGES:
        assert _approve(context, workspace, stage).status_code == 200
    context.client.get(context.approvals(workspace, "market_research"))
    context.client.delete(context.approvals(workspace, "market_research"))
    _status(context, workspace)

    assert context.llm.calls == baseline
