"""Real PostgreSQL integration tests for the stage approval service.

Uses the deterministic "local" LLM and embeddings providers and no
Tavily key, so this file is about the approval rules against real stage
records and a real database, not about model quality. Each test gets a
workspace whose seven stages were generated by a real full-strategy run,
so every approval is pinned to a genuine record id and version.

The properties that only a real database can prove are the point:

- an approval retires itself when its stage record changes, including
  the trap where a deleted-and-regenerated stage restarts at the same
  version number and only its new record id tells it apart;
- approving never touches the stage record it approves;
- the unique constraint turns two simultaneous approvals into one
  approval, deterministically simulated by interleaving two sessions.

HTTP routes for approval arrive in a later commit and are tested with
the rest of the API; this file calls the service directly.
"""

import os
from collections.abc import Callable, Iterator
from contextlib import contextmanager
from dataclasses import dataclass
from typing import Any
from uuid import UUID, uuid4

import pytest
from fastapi.testclient import TestClient
from sqlalchemy import delete, func, select

from backend.app.config import Settings
from backend.app.db.database import Database
from backend.app.db.models.market_research import MarketResearch
from backend.app.db.models.stage_approval import StageApproval
from backend.app.db.models.workspace import Workspace
from backend.app.exceptions import (
    ApprovalRequiredError,
    ResourceConflictError,
    ResourceNotFoundError,
    StaleResourceError,
)
from backend.app.main import create_application
from backend.app.schemas.stage_approval import ApprovalSource
from backend.app.schemas.strategy_orchestration import StrategyStage
from backend.app.services.stage_approval import StageApprovalService
from backend.app.services.strategy_status import STAGE_PREREQUISITES, unapproved_prerequisites

RUN_INTEGRATION_TESTS = os.getenv("GROWTHCREW_RUN_INTEGRATION_TESTS") == "1"

pytestmark = [
    pytest.mark.integration,
    pytest.mark.skipif(
        not RUN_INTEGRATION_TESTS,
        reason=("Set GROWTHCREW_RUN_INTEGRATION_TESTS=1 to run PostgreSQL integration tests."),
    ),
]

S = StrategyStage
STAGES = list(StrategyStage)
MR = S.MARKET_RESEARCH


@dataclass
class Context:
    """An API client (used to create real stage records) and its settings."""

    client: TestClient
    settings: Settings

    def url(self, workspace_id: UUID, path: str) -> str:
        return f"/api/v1/workspaces/{workspace_id}/{path}"


@pytest.fixture
def context() -> Iterator[Context]:
    """Create an API client backed by real PostgreSQL and the local stubs."""

    settings = Settings(
        environment="test",
        llm_provider="local",
        embeddings_provider="local",
        tavily_api_key=None,
    )

    if settings.database_url is None:
        pytest.fail("GROWTHCREW_DATABASE_URL is required for integration tests.")

    with TestClient(create_application(settings)) as client:
        yield Context(client=client, settings=settings)


def _cleanup(settings: Settings, workspace_id: UUID) -> None:
    """Remove only test-created data after an integration test."""

    database = Database.from_settings(settings)
    try:
        with database.session() as session:
            workspace = session.get(Workspace, workspace_id)
            if workspace is not None:
                session.delete(workspace)
                session.commit()
    finally:
        database.dispose()


def _new_workspace(ctx: Context, name: str, *, generate: bool) -> UUID:
    """Create a workspace with a profile, optionally with all seven stages generated."""

    response = ctx.client.post("/api/v1/workspaces", json={"name": name})
    assert response.status_code == 201
    workspace_id = UUID(response.json()["id"])

    profile = ctx.client.post(
        ctx.url(workspace_id, "business-profile"),
        json={"business_name": name, "industry": "Healthy Snacks"},
    )
    assert profile.status_code == 201

    if generate:
        run = ctx.client.post(
            ctx.url(workspace_id, "generate-full-strategy"),
            json={"force_regenerate": False},
        )
        assert run.status_code == 200
        assert [item["outcome"] for item in run.json()["stages"]] == ["generated"] * 7

    return workspace_id


@pytest.fixture
def workspace(context: Context) -> Iterator[UUID]:
    """A workspace with every stage generated and nothing approved."""

    workspace_id = _new_workspace(context, "Approval Service Co", generate=True)
    yield workspace_id
    _cleanup(context.settings, workspace_id)


@pytest.fixture
def bare_workspace(context: Context) -> Iterator[UUID]:
    """A workspace with a profile but no generated stages."""

    workspace_id = _new_workspace(context, "Approval Bare Co", generate=False)
    yield workspace_id
    _cleanup(context.settings, workspace_id)


@contextmanager
def _service(settings: Settings) -> Iterator[StageApprovalService]:
    """Yield an approval service on its own real session."""

    database = Database.from_settings(settings)
    try:
        with database.session() as session:
            yield StageApprovalService(session)
    finally:
        database.dispose()


def _status(ctx: Context, workspace_id: UUID) -> dict[str, Any]:
    response = ctx.client.get(ctx.url(workspace_id, "strategy-status"))
    assert response.status_code == 200
    return response.json()


def _by_stage(status: dict[str, Any]) -> dict[str, dict[str, Any]]:
    return {item["stage"]: item for item in status["stages"]}


def _version(ctx: Context, workspace_id: UUID, stage: StrategyStage) -> int:
    return int(_by_stage(_status(ctx, workspace_id))[stage.value]["version"])


def _approve(
    ctx: Context,
    workspace_id: UUID,
    stage: StrategyStage,
    *,
    source: ApprovalSource = ApprovalSource.HUMAN,
) -> StageApproval:
    """Approve a stage at its current version, as a reviewer looking at it would."""

    version = _version(ctx, workspace_id, stage)
    with _service(ctx.settings) as service:
        return service.approve(workspace_id, stage, version, source=source)


def _approval_rows(settings: Settings, workspace_id: UUID) -> list[StageApproval]:
    database = Database.from_settings(settings)
    try:
        with database.session() as session:
            return list(
                session.scalars(
                    select(StageApproval).where(StageApproval.workspace_id == workspace_id)
                )
            )
    finally:
        database.dispose()


def _change_market_research(settings: Settings, workspace_id: UUID) -> None:
    """Edit the market research record in place, bumping its version."""

    database = Database.from_settings(settings)
    try:
        with database.session() as session:
            record = session.scalars(
                select(MarketResearch).where(MarketResearch.workspace_id == workspace_id)
            ).one()
            record.model_used = "edited-after-approval"
            session.commit()
    finally:
        database.dispose()


def _market_research_record(settings: Settings, workspace_id: UUID) -> MarketResearch:
    database = Database.from_settings(settings)
    try:
        with database.session() as session:
            return session.scalars(
                select(MarketResearch).where(MarketResearch.workspace_id == workspace_id)
            ).one()
    finally:
        database.dispose()


def _delete_market_research(settings: Settings, workspace_id: UUID) -> None:
    database = Database.from_settings(settings)
    try:
        with database.session() as session:
            session.execute(
                delete(MarketResearch).where(MarketResearch.workspace_id == workspace_id)
            )
            session.commit()
    finally:
        database.dispose()


# --- status reflects approval -------------------------------------------------


def test_status_reports_every_generated_stage_as_draft(context: Context, workspace: UUID) -> None:
    """Freshly generated stages await review: nothing is approved by default."""

    status = _status(context, workspace)

    assert [item["approval"] for item in status["stages"]] == ["draft"] * 7
    assert status["approved"] is False
    assert status["next_to_approve"] == "business_understanding"


def test_status_reports_no_approval_for_stages_that_do_not_exist(
    context: Context, bare_workspace: UUID
) -> None:
    """Nothing to approve before generation, and nothing is awaiting review."""

    status = _status(context, bare_workspace)

    assert [item["approval"] for item in status["stages"]] == [None] * 7
    assert status["approved"] is False
    assert status["next_to_approve"] is None


def test_approving_a_stage_shows_in_status_and_advances_the_review_pointer(
    context: Context, workspace: UUID
) -> None:
    """Approving one stage flips only that stage and moves next_to_approve along."""

    _approve(context, workspace, S.BUSINESS_UNDERSTANDING)

    status = _status(context, workspace)
    approvals = {stage: item["approval"] for stage, item in _by_stage(status).items()}

    assert approvals["business_understanding"] == "approved"
    assert all(approvals[stage.value] == "draft" for stage in STAGES[1:])
    assert status["next_to_approve"] == "market_research"


def test_approving_every_stage_marks_the_whole_strategy_approved(
    context: Context, workspace: UUID
) -> None:
    """Seven approvals make the chain fully approved with nothing left to review."""

    for stage in STAGES:
        _approve(context, workspace, stage)

    status = _status(context, workspace)

    assert [item["approval"] for item in status["stages"]] == ["approved"] * 7
    assert status["approved"] is True
    assert status["next_to_approve"] is None


def test_approvals_are_scoped_to_their_workspace(context: Context, workspace: UUID) -> None:
    """Approving in one workspace must never approve the same stage in another."""

    other = _new_workspace(context, "Approval Other Co", generate=True)
    try:
        _approve(context, workspace, MR)

        assert _by_stage(_status(context, workspace))[MR.value]["approval"] == "approved"
        assert _by_stage(_status(context, other))[MR.value]["approval"] == "draft"
    finally:
        _cleanup(context.settings, other)


# --- approve ------------------------------------------------------------------


def test_approve_pins_the_approval_to_the_exact_record_and_version(
    context: Context, workspace: UUID
) -> None:
    """The stored approval names the record and version that were reviewed."""

    approval = _approve(context, workspace, MR)
    record = _market_research_record(context.settings, workspace)

    assert approval.workspace_id == workspace
    assert approval.stage == "market_research"
    assert approval.record_id == record.id
    assert approval.approved_version == record.version
    assert approval.source == "human"


def test_approving_never_touches_the_stage_record(context: Context, workspace: UUID) -> None:
    """Approval lives beside the artifact: its version and updated_at must not move."""

    before = _market_research_record(context.settings, workspace)

    _approve(context, workspace, MR)

    after = _market_research_record(context.settings, workspace)
    assert after.version == before.version
    assert after.updated_at == before.updated_at


def test_approve_for_a_stage_that_was_not_generated_is_404(
    context: Context, bare_workspace: UUID
) -> None:
    """There is nothing to approve yet, and no approval row is written."""

    with _service(context.settings) as service, pytest.raises(ResourceNotFoundError) as caught:
        service.approve(bare_workspace, MR, 1)

    assert str(caught.value) == "The market research stage has not been generated yet."
    assert _approval_rows(context.settings, bare_workspace) == []


def test_approve_in_an_unknown_workspace_is_404(context: Context) -> None:
    """A workspace that does not exist cannot have approvals."""

    with _service(context.settings) as service, pytest.raises(ResourceNotFoundError) as caught:
        service.approve(uuid4(), MR, 1)

    assert str(caught.value) == "Workspace not found."


def test_approve_at_a_version_that_is_not_current_is_refused(
    context: Context, workspace: UUID
) -> None:
    """A reviewer can only approve the version they actually looked at."""

    current = _version(context, workspace, MR)

    with _service(context.settings) as service, pytest.raises(StaleResourceError) as caught:
        service.approve(workspace, MR, current + 1)

    assert str(caught.value) == (
        f"The market research stage is now at version {current}, not version {current + 1}. "
        "Review the latest version before approving it."
    )
    assert _approval_rows(context.settings, workspace) == []


def test_approving_twice_is_idempotent_and_does_not_churn_the_timestamp(
    context: Context, workspace: UUID
) -> None:
    """A repeat approval of the same record and version changes nothing at all."""

    first = _approve(context, workspace, MR)
    second = _approve(context, workspace, MR)

    rows = _approval_rows(context.settings, workspace)
    assert len(rows) == 1
    assert second.id == first.id
    assert rows[0].approved_at == first.approved_at


def test_a_person_approving_upgrades_an_auto_approval_to_human(
    context: Context, workspace: UUID
) -> None:
    """Human review supersedes an automatic approval of the same record."""

    auto = _approve(context, workspace, MR, source=ApprovalSource.AUTO)
    assert auto.source == "auto"

    human = _approve(context, workspace, MR, source=ApprovalSource.HUMAN)

    rows = _approval_rows(context.settings, workspace)
    assert len(rows) == 1
    assert human.source == "human"
    assert rows[0].source == "human"


def test_auto_approval_never_downgrades_a_human_approval(context: Context, workspace: UUID) -> None:
    """Once a person approved a record, an automatic approval leaves it alone."""

    _approve(context, workspace, MR, source=ApprovalSource.HUMAN)

    again = _approve(context, workspace, MR, source=ApprovalSource.AUTO)

    assert again.source == "human"
    assert [row.source for row in _approval_rows(context.settings, workspace)] == ["human"]


# --- an approval retires itself with its record --------------------------------


def test_changing_the_record_retires_its_approval(context: Context, workspace: UUID) -> None:
    """Editing an approved stage returns it to draft with no reset logic anywhere."""

    _approve(context, workspace, MR)
    assert _by_stage(_status(context, workspace))[MR.value]["approval"] == "approved"

    _change_market_research(context.settings, workspace)

    stage = _by_stage(_status(context, workspace))[MR.value]
    assert stage["version"] == 2
    assert stage["approval"] == "draft"


def test_a_retired_approval_cannot_be_read_back_as_current(
    context: Context, workspace: UUID
) -> None:
    """get() treats a stale approval exactly like the status endpoint: not approved."""

    _approve(context, workspace, MR)
    _change_market_research(context.settings, workspace)

    with _service(context.settings) as service, pytest.raises(ResourceNotFoundError) as caught:
        service.get(workspace, MR)

    assert str(caught.value) == "The market research stage is not approved."


def test_reapproving_a_changed_stage_replaces_the_old_approval_in_place(
    context: Context, workspace: UUID
) -> None:
    """One row per stage: approving the new version reuses the row, never adds one."""

    first = _approve(context, workspace, MR)
    _change_market_research(context.settings, workspace)

    second = _approve(context, workspace, MR)

    rows = _approval_rows(context.settings, workspace)
    assert len(rows) == 1
    assert second.id == first.id
    assert rows[0].approved_version == 2
    assert _by_stage(_status(context, workspace))[MR.value]["approval"] == "approved"


def test_a_deleted_and_regenerated_stage_at_the_same_version_is_not_approved(
    context: Context, workspace: UUID
) -> None:
    """Regenerating from scratch restarts at version 1; only the record id differs.

    This is the trap that matching on version alone would fall into: the
    new record has the very version number that was approved, but it is
    different content nobody has reviewed.
    """

    approved = _approve(context, workspace, MR)
    assert approved.approved_version == 1

    _delete_market_research(context.settings, workspace)
    regenerated = context.client.post(context.url(workspace, "market-research"), json={})
    assert regenerated.status_code in {200, 201}

    stage = _by_stage(_status(context, workspace))[MR.value]
    assert stage["version"] == 1
    assert stage["approval"] == "draft"
    assert _market_research_record(context.settings, workspace).id != approved.record_id


def test_approving_a_recreated_stage_replaces_the_orphaned_approval(
    context: Context, workspace: UUID
) -> None:
    """The leftover row from the deleted record is reused, not accumulated."""

    first = _approve(context, workspace, MR)
    _delete_market_research(context.settings, workspace)
    context.client.post(context.url(workspace, "market-research"), json={})

    second = _approve(context, workspace, MR)

    rows = _approval_rows(context.settings, workspace)
    assert len(rows) == 1
    assert second.id == first.id
    assert rows[0].record_id != first.record_id
    assert _by_stage(_status(context, workspace))[MR.value]["approval"] == "approved"


# --- get ----------------------------------------------------------------------


def test_get_returns_the_current_approval(context: Context, workspace: UUID) -> None:
    """A current approval can be read back with who recorded it and for which record."""

    approved = _approve(context, workspace, MR, source=ApprovalSource.AUTO)

    with _service(context.settings) as service:
        fetched = service.get(workspace, MR)

    assert fetched.id == approved.id
    assert fetched.source == "auto"


def test_get_for_an_unapproved_stage_is_404(context: Context, workspace: UUID) -> None:
    """Draft stages have no approval to return."""

    with _service(context.settings) as service, pytest.raises(ResourceNotFoundError):
        service.get(workspace, MR)


# --- revoke -------------------------------------------------------------------


def test_revoke_returns_the_stage_to_draft(context: Context, workspace: UUID) -> None:
    """Pulling back an approval makes the stage await review again."""

    _approve(context, workspace, MR)

    with _service(context.settings) as service:
        service.revoke(workspace, MR)

    assert _by_stage(_status(context, workspace))[MR.value]["approval"] == "draft"
    assert _approval_rows(context.settings, workspace) == []


def test_revoke_leaves_other_stages_approved(context: Context, workspace: UUID) -> None:
    """Revoking one stage must not disturb the approvals of the rest."""

    _approve(context, workspace, S.BUSINESS_UNDERSTANDING)
    _approve(context, workspace, MR)

    with _service(context.settings) as service:
        service.revoke(workspace, MR)

    approvals = {s: i["approval"] for s, i in _by_stage(_status(context, workspace)).items()}
    assert approvals["business_understanding"] == "approved"
    assert approvals["market_research"] == "draft"


def test_revoke_is_idempotent(context: Context, workspace: UUID) -> None:
    """Revoking a stage that has no approval succeeds quietly, any number of times."""

    with _service(context.settings) as service:
        service.revoke(workspace, MR)
        service.revoke(workspace, MR)

    _approve(context, workspace, MR)

    with _service(context.settings) as service:
        service.revoke(workspace, MR)
        service.revoke(workspace, MR)

    assert _approval_rows(context.settings, workspace) == []


def test_revoke_also_clears_a_stale_leftover_approval(context: Context, workspace: UUID) -> None:
    """A retired approval row is still removed, so no orphans linger."""

    _approve(context, workspace, MR)
    _change_market_research(context.settings, workspace)
    assert len(_approval_rows(context.settings, workspace)) == 1

    with _service(context.settings) as service:
        service.revoke(workspace, MR)

    assert _approval_rows(context.settings, workspace) == []


def test_revoke_in_an_unknown_workspace_is_404(context: Context) -> None:
    """A workspace that does not exist cannot have approvals revoked."""

    with _service(context.settings) as service, pytest.raises(ResourceNotFoundError):
        service.revoke(uuid4(), MR)


# --- require_prerequisites_approved -------------------------------------------


@pytest.mark.parametrize("stage", STAGES)
def test_gate_walks_through_each_prerequisite_until_the_stage_is_unblocked(
    context: Context, workspace: UUID, stage: StrategyStage
) -> None:
    """For every stage: blocked on exactly its outstanding prerequisites, then clear.

    Approves the stage's prerequisites one at a time and checks after each
    step that the reported blockers are exactly the ones still draft, using
    the real prerequisite map rather than hand-written expectations.
    """

    prerequisites = [
        S(item.value) for item in STAGE_PREREQUISITES[stage] if item.value != "business_profile"
    ]
    approved: set[StrategyStage] = set()

    for next_to_approve in [*prerequisites, None]:
        outstanding = unapproved_prerequisites(stage, approved)

        with _service(context.settings) as service:
            if outstanding:
                with pytest.raises(ApprovalRequiredError) as caught:
                    service.require_prerequisites_approved(workspace, stage)
                assert caught.value.stage == stage.value
                assert list(caught.value.unapproved) == [item.value for item in outstanding]
            else:
                service.require_prerequisites_approved(workspace, stage)

        if next_to_approve is not None:
            _approve(context, workspace, next_to_approve)
            approved.add(next_to_approve)

    assert unapproved_prerequisites(stage, approved) == []


def test_gate_message_names_the_blocking_stages(context: Context, workspace: UUID) -> None:
    """The client-facing text says exactly what to approve first."""

    with _service(context.settings) as service, pytest.raises(ApprovalRequiredError) as caught:
        service.require_prerequisites_approved(workspace, S.BRAND_STRATEGY)

    assert str(caught.value) == (
        "Approve the business understanding, competitor analysis and customer personas "
        "stages before generating the brand strategy stage."
    )


def test_gate_does_not_care_whether_the_stage_itself_is_approved(
    context: Context, workspace: UUID
) -> None:
    """Only what a stage builds on matters, never its own review state."""

    _approve(context, workspace, S.CONTENT_PLAN)

    with _service(context.settings) as service, pytest.raises(ApprovalRequiredError) as caught:
        service.require_prerequisites_approved(workspace, S.CONTENT_PLAN)

    assert caught.value.unapproved == ("marketing_strategy",)


def test_changing_a_prerequisite_blocks_its_dependents_again(
    context: Context, workspace: UUID
) -> None:
    """Once an approved prerequisite changes, the stages built on it are gated afresh."""

    _approve(context, workspace, S.BUSINESS_UNDERSTANDING)
    _approve(context, workspace, MR)

    with _service(context.settings) as service:
        service.require_prerequisites_approved(workspace, S.CUSTOMER_PERSONAS)

    _change_market_research(context.settings, workspace)

    with _service(context.settings) as service, pytest.raises(ApprovalRequiredError) as caught:
        service.require_prerequisites_approved(workspace, S.CUSTOMER_PERSONAS)

    assert caught.value.unapproved == ("market_research",)


# --- concurrency ---------------------------------------------------------------


def _interleaved_approval(
    settings: Settings,
    workspace_id: UUID,
    version: int,
    *,
    winner: Callable[[Any, UUID], None],
) -> StageApproval:
    """Run approve() on one session while another "wins the race" mid-flight.

    Wraps the first approval lookup of the racing service so that, right
    after it reports that no approval exists, the winner callback commits
    a competing approval from a second session. The racing service then
    inserts its own row and hits the unique constraint - the exact
    interleaving of two simultaneous requests, made deterministic.
    """

    database_a = Database.from_settings(settings)
    database_b = Database.from_settings(settings)
    try:
        with database_a.session() as session_a, database_b.session() as session_b:
            service = StageApprovalService(session_a)
            repository = service._approvals
            original = repository.get_by_workspace_and_stage
            raced = {"done": False}

            def racing(workspace: UUID, stage: str) -> StageApproval | None:
                result = original(workspace, stage)
                if not raced["done"]:
                    raced["done"] = True
                    winner(session_b, workspace)
                return result

            repository.get_by_workspace_and_stage = racing  # type: ignore[method-assign]
            return service.approve(workspace_id, MR, version)
    finally:
        database_a.dispose()
        database_b.dispose()


def test_two_simultaneous_approvals_of_the_same_record_settle_to_one(
    context: Context, workspace: UUID
) -> None:
    """If another request approves the same record first, this one returns that approval."""

    version = _version(context, workspace, MR)

    def winner(session: Any, workspace_id: UUID) -> None:
        StageApprovalService(session).approve(workspace_id, MR, version)

    result = _interleaved_approval(context.settings, workspace, version, winner=winner)

    rows = _approval_rows(context.settings, workspace)
    assert len(rows) == 1
    assert result.id == rows[0].id
    assert rows[0].approved_version == version


def test_a_race_lost_to_a_different_approval_is_reported_as_a_conflict(
    context: Context, workspace: UUID
) -> None:
    """If what won the race is not an approval of this record, say so instead of guessing."""

    version = _version(context, workspace, MR)

    def winner(session: Any, workspace_id: UUID) -> None:
        session.add(
            StageApproval(
                workspace_id=workspace_id,
                stage=MR.value,
                record_id=uuid4(),
                approved_version=version + 40,
            )
        )
        session.commit()

    with pytest.raises(ResourceConflictError) as caught:
        _interleaved_approval(context.settings, workspace, version, winner=winner)

    assert str(caught.value) == (
        "The market research stage's approval was changed by another request. Try again."
    )
    assert len(_approval_rows(context.settings, workspace)) == 1


# --- cleanup of approvals with their workspace ----------------------------------


def test_deleting_the_workspace_removes_its_approvals(context: Context) -> None:
    """Approvals must not outlive the workspace they belong to."""

    workspace_id = _new_workspace(context, "Approval Cascade Co", generate=True)
    try:
        for stage in STAGES[:3]:
            _approve(context, workspace_id, stage)
        assert len(_approval_rows(context.settings, workspace_id)) == 3
    finally:
        _cleanup(context.settings, workspace_id)

    database = Database.from_settings(context.settings)
    try:
        with database.session() as session:
            remaining = session.scalar(
                select(func.count())
                .select_from(StageApproval)
                .where(StageApproval.workspace_id == workspace_id)
            )
    finally:
        database.dispose()

    assert remaining == 0
